name: Build image

on:
  push:
    branches: [ openwrt-21.02-tweaks ]
  pull_request:
    branches: [ openwrt-21.02-tweaks ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |-
        apt-get update &&\
        apt-get install -y \
        sudo time git-core subversion build-essential g++ bash make \
        libssl-dev patch libncurses5 libncurses5-dev zlib1g-dev gawk \
        flex gettext wget unzip xz-utils python python-distutils-extra \
        python3 python3-distutils-extra rsync curl libsnmp-dev liblzma-dev \
        libpam0g-dev cpio rsync
    - name: test
      run: touch ${HOME}/abc
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ${HOME}/abc
