name: Build image

on:
  push:
    branches: [ openwrt-21.02-tweaks ]
  pull_request:
    branches: [ openwrt-21.02-tweaks ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${{ github.sha }} > Release.txt
        echo "hello" > file.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          file.txt
    # - name: install dependencies
    #   run: |
    #     sudo apt-get update &&\
    #     sudo apt-get install -y \
    #     time git-core subversion build-essential g++ bash make \
    #     libssl-dev patch libncurses5 libncurses5-dev zlib1g-dev gawk \
    #     flex gettext wget unzip xz-utils python python-distutils-extra \
    #     python3 python3-distutils-extra rsync curl libsnmp-dev liblzma-dev \
    #     libpam0g-dev cpio rsync
    # - name: initialize build image
    #   run: |
    #     ./scripts/feeds update -a &&\
    #     ./scripts/feeds install -a
    # - name: prep config
    #   run: |
    #     cp configs/OrangePi_R1_Plus_LTS_defconfig .config &&\
    #     make defconfig
    # - name: build using make
    #   run: make -j $(nproc)
    # - name: generate artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: openwrt-image
    #     path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-*